# Generated by Django 2.1.3 on 2018-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coinform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('price_entry', models.DecimalField(decimal_places=10, max_digits=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=100, null=True)),
                ('total_value', models.DecimalField(decimal_places=10, max_digits=100, null=True)),
                ('date_purchase', models.DateField(auto_now=True)),
            ],
        ),
    ]
