# Generated by Django 2.1.3 on 2018-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_coinform_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolio',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
