# Generated by Django 2.1.3 on 2018-12-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20181209_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinform',
            name='username',
        ),
        migrations.RemoveField(
            model_name='porfolio',
            name='username',
        ),
    ]
