# Generated by Django 2.1.3 on 2018-12-06 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_coinform_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('total_quantity', models.DecimalField(decimal_places=5, max_digits=30, null=True)),
                ('total_value', models.DecimalField(decimal_places=5, max_digits=30, null=True)),
                ('profit', models.DecimalField(decimal_places=5, max_digits=30, null=True)),
                ('percentchange', models.FloatField(null=True)),
                ('OwnerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Coinform')),
            ],
        ),
    ]
