# Generated by Django 2.1.3 on 2018-12-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_porfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinform',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
