# Generated by Django 2.1.3 on 2018-12-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_porfolio_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinform',
            name='current_price',
            field=models.DecimalField(decimal_places=10, max_digits=100, null=True),
        ),
    ]
