# Generated by Django 2.1.3 on 2018-12-09 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0006_coinform_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfolio',
            name='OwnerID',
        ),
        migrations.AddField(
            model_name='porfolio',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
